sjtug/SJTUBeamer

- README.md
- main.tex
在这个 PR 中，Beamer 配色修改成了 SJTU Logo 的颜色。文档环境换成 ctexbeamer，且默认生成 16:9 的 slides。
[main.pdf](https://github.com/sjtug/SJTUBeamer/files/6508489/main.pdf)
> style: refine template

- main.tex
The extension should be avoided in `\include`. It doesn't work both locally and using Overleaf.
> fix(main.tex): remove the extension in \include

- beamercolorthemesjtubeamer.sty
- beamerfontthemesjtubeamer.sty
- beamerinnerthemesjtubeamer.sty
- beamerouterthemesjtubeamer.sty
- beamerthemesjtubeamer.sty
- sjtucover.sty
- sjtuvi.sty
- src/build.lua
- src/doc/sjtubeamer.tex
- src/doc/sjtubeamerdevguide.tex
- src/source/beamercolorthemesjtubeamer.dtx
- src/source/beamerfontthemesjtubeamer.dtx
- src/source/beamerinnerthemesjtubeamer.dtx
- src/source/beamerouterthemesjtubeamer.dtx
- src/source/beamerthemesjtubeamer.dtx
- src/source/latexmkrc
- src/source/sjtucover.dtx
- src/source/sjtuvi.dtx
- src/support/tutorial/step12.tex
由于底部的工具栏重写（为了不与脚注碰撞），导致 logo 需要换一个地方显示。
- 使用 `maxplus` 会连带logo为右上角显示。
- 使用 `max` 会连带logo为右下角显示。
- 使用 `min` 会连带logo为右上角显示。
- 使用 `my` 会连带logo为右下角显示。
也可以分别使用 `bottomright`, `topright` 覆盖显示选项。
如果打开了 `--shell-escape` 编译开关，将会对 tikz 图像进行缓存。对内部一些不必缓存的元素进行了保护。由于处于实验性阶段，默认将会关闭。
> feat: logo position

- README.md
- README_en.md
- beamercolorthemesjtubeamer.sty
- beamerfontthemesjtubeamer.sty
- beamerinnerthemesjtubeamer.sty
- beamerouterthemesjtubeamer.sty
- beamerthemesjtubeamer.sty
- main.tex
- sjtucover.sty
- sjtuvi.sty
- src/build.lua
- src/doc/sjtubeamer.tex
- src/source/beamercolorthemesjtubeamer.dtx
- src/source/beamerfontthemesjtubeamer.dtx
- src/source/beamerinnerthemesjtubeamer.dtx
- src/source/beamerouterthemesjtubeamer.dtx
- src/source/beamerthemesjtubeamer.dtx
- src/source/sjtucover.dtx
- src/source/sjtuvi.dtx
- src/support/tutorial/stepcache.tex
最新的版本在 Overleaf 上会被默认开启缓存，现在改为需要用户手动在主文档开启缓存，并且在根目录预留了 cache 文件夹与其内的 dummy file，这样才能让在线编译器正常运转缓存，详见 [相关说明](https://www.overleaf.com/learn/latex/Questions/I_have_a_lot_of_tikz%2C_matlab2tikz_or_pgfplots_figures%2C_so_I%27m_getting_a_compilation_timeout._Can_I_externalise_my_figures%3F)，应当被认为是一些内部机制导致的。
[SJTU LaTeX 文档助手](https://latex.sjtu.edu.cn/)采用的是 2.0.0 稳定版，不会有相关问题，详见 [工程链接](https://latex.sjtu.edu.cn/read/qtjvvcdktrns)（点开后回到主界面，在项目列表里打开模板，在右上角“更多的”里选择“制作一份拷贝”即可开始编辑）。
> fix: tikz externalization on Overleaf

- .gitattributes
- .gitignore
- .vscode/sjtubeamer.code-snippets
- beamercolorthemesjtubeamer.sty
- beamerfontthemesjtubeamer.sty
- beamerinnerthemesjtubeamer.sty
- beamerouterthemesjtubeamer.sty
- beamerthemesjtubeamer.sty
- sjtucover.sty
- sjtuvi.sty
- src/build.lua
- src/doc/sjtubeamer.tex
- src/doc/sjtubeamerdevguide.tex
- src/source/beamercolorthemesjtubeamer.dtx
- src/source/beamerfontthemesjtubeamer.dtx
- src/source/beamerinnerthemesjtubeamer.dtx
- src/source/beamerouterthemesjtubeamer.dtx
- src/source/beamerthemesjtubeamer.dtx
- src/source/sjtucover.dtx
- src/source/sjtuvi.dtx
该 PR 添加了对于 dtx 文件的 [VS Code Snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets) 编译器。在 `l3build check` 阶段生成。
`.vscode/sjtubeamer.code-snippets` 文件在 `l3build check` 阶段生成，会在输入对应的触发前缀（prefix）时提供代码补全提示，提示内容根据 `macro` 环境的第一段内容生成（`macrocode` 之前的内容）。为了让这个简易的编译器正常运行，源代码（dtx）需要遵循开发文档中的代码风格规则。
> beamer 自身的 snippets 由 [LaTeX-Workshop](https://github.com/James-Yu/LaTeX-Workshop) 扩展提供。
> 按照道理，模板不应当在编辑器上有偏好，专有编辑器如 TeX Studio, TeX Works 并没有提供类似的扩展方法，其他的编辑器如 Vim 等或许会在未来的一些时机通过 [Language Server Protocol](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide) 以获得跨编辑器的代码补全支持（还在考虑）。
> 发布包不包含 code snippets。
> feat: VS Code snippets

- .vscode/sjtubeamer.code-snippets
- beamercolorthemesjtubeamer.sty
- beamerfontthemesjtubeamer.sty
- beamerinnerthemesjtubeamer.sty
- beamerouterthemesjtubeamer.sty
- beamerthemesjtubeamer.sty
- contrib/sjtug/sjtubeamerthemesjtug.ltx
- sjtucover.sty
- sjtuvi.sty
- src/doc/sjtubeamer.tex
- src/doc/sjtubeamerdevguide.tex
- src/source/beamercolorthemesjtubeamer.dtx
- src/source/beamerfontthemesjtubeamer.dtx
- src/source/beamerinnerthemesjtubeamer.dtx
- src/source/beamerouterthemesjtubeamer.dtx
- src/source/beamerthemesjtubeamer.dtx
- src/source/sjtucover.dtx
- src/source/sjtuvi.dtx
- src/support/tutorial/my.sty
本 PR 重构了 Logo Color System，删去了全局变量 `\sjtubeamer@logocolor`，改为 logo 随着文本颜色的变化而变化。
- 对于创建出来的徽标原语，仍然可以使用可选参数更改徽标颜色，`\cnlogo[cprimary]`。
- 对于 `\insertlogo` 而言，会调用 `\usebeamertemplate*{logo}` 而采用 color theme 里的 logo.fg 控制默认颜色。
- 想要更改 `\insertlogo` （不接受参数）的颜色，需要改用 `\usebeamertemplate{logo}`，并在此之前修改文本颜色。
本 PR 也重载了 `beamer` 中的 `\titlegraphic` 定义，改为使用 beamer template，下沉了 logo 和 titlegraphic 到 cover 中以统一管理这些模板。
修改了插件里的一处徽标插入，添加了颜色参数。将会在下面的 PR 中逐步完成插件的范例完善，这个 PR 就不再检查该插件。
> refactor: logo color system

- .vscode/sjtubeamer.code-snippets
- beamercolorthemesjtubeamer.sty
- beamerfontthemesjtubeamer.sty
- beamerinnerthemesjtubeamer.sty
- beamerouterthemesjtubeamer.sty
- beamerthemesjtubeamer.sty
- sjtucover.sty
- sjtuvi.sty
- src/doc/sjtubeamer.tex
- src/source/beamercolorthemesjtubeamer.dtx
- src/source/beamerfontthemesjtubeamer.dtx
- src/source/beamerinnerthemesjtubeamer.dtx
- src/source/beamerouterthemesjtubeamer.dtx
- src/source/beamerthemesjtubeamer.dtx
- src/source/sjtucover.dtx
- src/source/sjtuvi.dtx
- src/support/tutorial/commonheader.tex
- src/support/tutorial/step10.tex
- src/support/tutorial/step12.tex
本 PR 重构了高亮区块：
- `\highlight[]{}` 和 `\paragraph` 用 `xcolor` 中的 `\colorbox` 重写，不再使用 `tcolorbox` 以期得到更好的性能。
- `codeblock` 边距做出微小变动，并添加 `\highlightline` 宏可用于高亮当前代码行。
- `\stamptext{}` 添加该宏用于生成 vi 图形区块。
> refactor: highlighters

- .vscode/sjtubeamer.code-snippets
- beamercolorthemesjtubeamer.sty
- beamerfontthemesjtubeamer.sty
- beamerinnerthemesjtubeamer.sty
- beamerouterthemesjtubeamer.sty
- beamerthemesjtubeamer.sty
- contrib/minted/minted.tex
- contrib/minted/sjtubeamerthememinted.ltx
- sjtucover.sty
- sjtuvi.sty
- src/build.lua
- src/source/beamercolorthemesjtubeamer.dtx
- src/source/beamerfontthemesjtubeamer.dtx
- src/source/beamerinnerthemesjtubeamer.dtx
- src/source/beamerouterthemesjtubeamer.dtx
- src/source/beamerthemesjtubeamer.dtx
- src/source/sjtucover.dtx
- src/source/sjtuvi.dtx
本 PR 
- 修复 codeblock 环境的 `breakable` 将会导致使用 `columns` 另一列无法显示的问题，已经去除。
- 对 `\highlight` 和 `\highlightline` 添加 overlay option，可以采用可选的 `<#1>` 用于指示在哪一页显示。
- 对于 cover 将会强制 parindent 为 0 以避免偏移。https://github.com/sjtug/SJTUBeamer/pull/88/commits/a6e7bb8230585b52e1736623fd2b601098ff0936
> fix: codeblock and overlay for highlight

- beamercolorthemesjtubeamer.sty
- beamerfontthemesjtubeamer.sty
- beamerinnerthemesjtubeamer.sty
- beamerouterthemesjtubeamer.sty
- beamerthemesjtubeamer.sty
- sjtucover.sty
- sjtuvi.sty
- src/source/beamercolorthemesjtubeamer.dtx
- src/source/beamerfontthemesjtubeamer.dtx
- src/source/beamerinnerthemesjtubeamer.dtx
- src/source/beamerouterthemesjtubeamer.dtx
- src/source/beamerthemesjtubeamer.dtx
- src/source/sjtucover.dtx
- src/source/sjtuvi.dtx
采用 `\insertsectionnavigationhorizontal` 宏而不是 `\insertnavigation` 来插入导航栏，防止溢出。
Before
After
> fix: part page navigation bar

- .vscode/sjtubeamer.code-snippets
- beamerinnerthemesjtubeamer.sty
- contrib/sjtug/sjtubeamerthemesjtug.ltx
- src/doc/sjtubeamer.tex
- src/source/beamerinnerthemesjtubeamer.dtx
- src/source/beamerthemesjtubeamer.ins
- src/support/tutorial/step16+-.tex
对 SJTUG 子主题添加 `shadedsection` 环境封装带阴影编号的 logo 图标。
更新一些文档内容。
PS: 最近 LaTeX Workshop 自带的 PDF 阅读器对透明度的实现可能有 BUG，使用其他软件打开 PDF 背景图片是较淡的正常透明度。
> contrib: shadedsection for sjtug theme

- .vscode/sjtubeamer.code-snippets
- beamercolorthemesjtubeamer.sty
- beamerfontthemesjtubeamer.sty
- beamerinnerthemesjtubeamer.sty
- beamerouterthemesjtubeamer.sty
- beamerthemesjtubeamer.sty
- contrib/sjtug/sjtubeamerthemesjtug.ltx
- sjtucover.sty
- sjtuvi.sty
- src/doc/sjtubeamer.tex
- src/source/beamercolorthemesjtubeamer.dtx
- src/source/beamerfontthemesjtubeamer.dtx
- src/source/beamerinnerthemesjtubeamer.dtx
- src/source/beamerouterthemesjtubeamer.dtx
- src/source/beamerthemesjtubeamer.dtx
- src/source/sjtucover.dtx
- src/source/sjtuvi.dtx
`\nointerlineskip` 会与 `beamer` 的 `\lecture{}{}` 与 `\includeonlylecture{}`冲突，需要移除封面页这样的代码：
```latex
% \nointerlineskip
\vbox{}
```
由于 `\nointerlineskip` 只会移除下一个盒子两端的间距，这两行代码或许会消除小间距，但是视觉区别不大。
似乎当时引入的时候只是为了消除 `beamercolorbox` 的间距，现在不需要了，#28 已经重构了该部分代码
https://github.com/sjtug/SJTUBeamer/blob/5001d991c06e647c7fc9165baa506d0d6fb1bf5c/beamerthemesjtubeamer.sty#L44-L45
杂项：
- `\articleitem`, `\bookitem`, `\onlineitem` 现在只可以在 `bibliolist` 中使用。
- 在文档中推荐 [pympress](https://github.com/Cimbali/pympress) 阅读器。
> fix: remove \nointerlineskip

- beamercolorthemesjtubeamer.sty
- beamerfontthemesjtubeamer.sty
- beamerinnerthemesjtubeamer.sty
- beamerouterthemesjtubeamer.sty
- beamerthemesjtubeamer.sty
- sjtucover.sty
- sjtuvi.sty
- src/source/beamercolorthemesjtubeamer.dtx
- src/source/beamerfontthemesjtubeamer.dtx
- src/source/beamerinnerthemesjtubeamer.dtx
- src/source/beamerouterthemesjtubeamer.dtx
- src/source/beamerthemesjtubeamer.dtx
- src/source/sjtucover.dtx
- src/source/sjtuvi.dtx
参照 [原样式文件](https://github.com/sjtug/sjtulib-latex-talk/blob/68e336580ac2126aaaeffba3efd61c6f9402bbf7/beamerthemesjtug.sty#L23-L26) 修复 beamer 默认设置下列表环境边距过大的问题。
|Before|After|
|---|---|
|<img width="243" alt="image" src="https://user-images.githubusercontent.com/61653082/167334226-db89b2f7-5c6c-49a2-81bd-6e082cbbbce2.png">|<img width="199" alt="image" src="https://user-images.githubusercontent.com/61653082/167334199-7fe84c6d-2893-40d0-95de-d4f5fa047bb5.png">|
> fix: itemmargin

- beamercolorthemesjtubeamer.sty
- beamerfontthemesjtubeamer.sty
- beamerinnerthemesjtubeamer.sty
- beamerouterthemesjtubeamer.sty
- beamerthemesjtubeamer.sty
- sjtucover.sty
- sjtuvi.sty
- src/doc/sjtubeamer.tex
- src/source/beamercolorthemesjtubeamer.dtx
- src/source/beamerfontthemesjtubeamer.dtx
- src/source/beamerinnerthemesjtubeamer.dtx
- src/source/beamerouterthemesjtubeamer.dtx
- src/source/beamerthemesjtubeamer.dtx
- src/source/sjtucover.dtx
- src/source/sjtuvi.dtx
在 `topright` 模式下减少标题栏的高度以让正文含有更多内容。但是 `default` 维持原本的设计。
|Before|After|
|---|---|
|<img width="550" alt="image" src="https://user-images.githubusercontent.com/61653082/167607022-d846982c-0494-408e-b020-f8b78c59fff7.png">|<img width="550" alt="image" src="https://user-images.githubusercontent.com/61653082/167606786-e742ade0-57d4-4e2f-af36-4378058244fb.png">|
> style: reduce frametitle height

- beamercolorthemesjtubeamer.sty
- beamerfontthemesjtubeamer.sty
- beamerinnerthemesjtubeamer.sty
- beamerouterthemesjtubeamer.sty
- beamerthemesjtubeamer.sty
- sjtucover.sty
- sjtuvi.sty
- src/doc/sjtubeamer.tex
- src/source/beamercolorthemesjtubeamer.dtx
- src/source/beamerfontthemesjtubeamer.dtx
- src/source/beamerinnerthemesjtubeamer.dtx
- src/source/beamerouterthemesjtubeamer.dtx
- src/source/beamerthemesjtubeamer.dtx
- src/source/sjtucover.dtx
- src/source/sjtuvi.dtx
修正 `maxplus` 节次页如果该帧没有被设定为 `plain` 会导致的偏移问题。
|Before|After|
|---|---|
|<img width="277" alt="image" src="https://user-images.githubusercontent.com/61653082/167618371-419cb501-9b62-4465-9d04-be16281e214c.png">|<img width="274" alt="image" src="https://user-images.githubusercontent.com/61653082/167630281-ecf29098-5a50-48a4-9ac9-bc7deb401cb0.png">|
> fix: maxplus sectioning page shift

- beamercolorthemesjtubeamer.sty
- beamerfontthemesjtubeamer.sty
- beamerinnerthemesjtubeamer.sty
- beamerouterthemesjtubeamer.sty
- beamerthemesjtubeamer.sty
- main.tex
- sjtucover.sty
- sjtuvi.sty
- src/doc/sjtubeamer.tex
- src/doc/sjtubeamerdevguide.tex
- src/source/beamercolorthemesjtubeamer.dtx
- src/source/beamerfontthemesjtubeamer.dtx
- src/source/beamerinnerthemesjtubeamer.dtx
- src/source/beamerouterthemesjtubeamer.dtx
- src/source/beamerthemesjtubeamer.dtx
- src/source/sjtucover.dtx
- src/source/sjtuvi.dtx
- src/support/tutorial/stepalgo.tex
- src/support/tutorial/stepalgorithm.tex
可能将 `\emph` 颜色使用红色有点奇怪，改用了 beamer 默认定义。
|Before|After|
|---|---|
|<img width="432" alt="image" src="https://user-images.githubusercontent.com/61653082/168467942-9953d0d2-f60a-4c33-b33a-de128cdd4fa7.png">|<img width="432" alt="image" src="https://user-images.githubusercontent.com/61653082/168467929-23e03a93-79a8-47dc-92b4-b30fb2d48242.png">|
> style: emph, comment and algorithm color

- beamercolorthemesjtubeamer.sty
- beamerfontthemesjtubeamer.sty
- beamerinnerthemesjtubeamer.sty
- beamerouterthemesjtubeamer.sty
- beamerthemesjtubeamer.sty
- sjtucover.sty
- sjtuvi.sty
- src/source/beamercolorthemesjtubeamer.dtx
- src/source/beamerfontthemesjtubeamer.dtx
- src/source/beamerinnerthemesjtubeamer.dtx
- src/source/beamerouterthemesjtubeamer.dtx
- src/source/beamerthemesjtubeamer.dtx
- src/source/sjtucover.dtx
- src/source/sjtuvi.dtx
> fix: min title page combo logo space

- beamercolorthemesjtubeamer.sty
- beamerfontthemesjtubeamer.sty
- beamerinnerthemesjtubeamer.sty
- beamerouterthemesjtubeamer.sty
- beamerthemesjtubeamer.sty
- main.tex
- sjtucover.sty
- sjtuvi.sty
- src/doc/sjtubeamer.tex
- src/source/beamercolorthemesjtubeamer.dtx
- src/source/beamerfontthemesjtubeamer.dtx
- src/source/beamerinnerthemesjtubeamer.dtx
- src/source/beamerouterthemesjtubeamer.dtx
- src/source/beamerthemesjtubeamer.dtx
- src/source/sjtucover.dtx
- src/source/sjtuvi.dtx
- src/support/tutorial/step6+.tex
- src/support/tutorial/step7+.tex
- src/support/tutorial/step9+.tex
采用新的目录样式。
||Before|After|
|---|---|---|
|总目录|<img width="376" alt="image" src="https://user-images.githubusercontent.com/61653082/168804176-f1b2e8f6-eb8f-46e3-bb8f-f1222bf502cb.png">|<img width="376" alt="image" src="https://user-images.githubusercontent.com/61653082/168804263-96b51ac8-1004-4d12-a91a-0bd268ac8a45.png">|
|节目录|<img width="376" alt="image" src="https://user-images.githubusercontent.com/61653082/168803129-a9133000-60f5-460b-9103-a1c0362c782c.png">|<img width="376" alt="image" src="https://user-images.githubusercontent.com/61653082/168803475-6dd8862b-9fc7-4f41-b9a2-70456a1e2056.png">|
|小节目录|<img width="376" alt="image" src="https://user-images.githubusercontent.com/61653082/168804420-51590baf-0aa7-4639-ac6d-81466a632636.png">|<img width="376" alt="image" …
> feat: stamp TOC style

- contents/basis.tex
- contents/introduction.tex
- contents/summary.tex
- contents/thesis.tex
- main.tex
- 在没有字体配置功能前，暂时去除主文档中的 `unicode-math` 宏包引用，暂时部分解决 #109
- 去除行内抄录（应当使用 `\verb|SOMETHING|` 而不使用省略版的 `|SOMETHING|`），以避免与绝对值输入的冲突，此时 `frame` 上仍然应当有 `fragile` 选项
- 不使用 `biblatex` 时，主文档可以使用 pdflatex 编译（使用 `gbt7714` 时，pdflatex 编译需要路径全英文）
> docs: remove some packages temporarily

- .vscode/sjtubeamer.code-snippets
- beamercolorthemesjtubeamer.sty
- beamerfontthemesjtubeamer.sty
- beamerinnerthemesjtubeamer.sty
- beamerouterthemesjtubeamer.sty
- beamerthemesjtubeamer.sty
- sjtucover.sty
- sjtuvi.sty
- src/build.lua
- src/doc/sjtubeamerdevguide.tex
- src/source/beamercolorthemesjtubeamer.dtx
- src/source/beamerfontthemesjtubeamer.dtx
- src/source/beamerinnerthemesjtubeamer.dtx
- src/source/beamerouterthemesjtubeamer.dtx
- src/source/beamerthemesjtubeamer.dtx
- src/source/sjtucover.dtx
- src/source/sjtuvi.dtx
- src/testfiles/sjtuvi.lvt
- src/testfiles/sjtuvi.tlg
将二级机构徽标抽象为宏 `\secondaryinstlogo`，便于后续调用。
```latex
\secondaryinstlogo[英文名]{中文名}{徽标}
\secondaryinstlogo{英文名}{徽标}
```
**重要修正**：清除 `\resizebox` 缩放 `\definelogo` 产生徽标产生的两侧多余空格。 a4c238e09e4825a5031be93a81fbb76abe1fa70c
> refactor: secondary institute logo

- .vscode/sjtubeamer.code-snippets
- beamercolorthemesjtubeamer.sty
- beamerfontthemesjtubeamer.sty
- beamerinnerthemesjtubeamer.sty
- beamerouterthemesjtubeamer.sty
- beamerthemesjtubeamer.sty
- sjtucover.sty
- sjtuvi.sty
- src/build.lua
- src/doc/sjtubeamer.tex
- src/source/beamercolorthemesjtubeamer.dtx
- src/source/beamerfontthemesjtubeamer.dtx
- src/source/beamerinnerthemesjtubeamer.dtx
- src/source/beamerouterthemesjtubeamer.dtx
- src/source/beamerthemesjtubeamer.dtx
- src/source/sjtucover.dtx
- src/source/sjtuvi.dtx
- src/testfiles/sjtuvi.lvt
- src/testfiles/sjtuvi.tlg
重构 `\secondaryinstlogo` 并正式可用。
```latex
% 中文样式
\secondaryinstlogo[英文名]{中文名}{徽标}
% 英文样式，此时英文名可用 \\ 换行，但不能用 \par 换行
\secondaryinstlogo{英文名}{徽标}
% 图片样式，图片高度需要为 0.95cm 高
\secondaryinstlogo{\resizebox{!}{0.95cm}{第二徽标}}{徽标}
```
细节：
- 使用 `tabular` 环境排印英文机构名可能的换行情况，这样将会自动设置该“文本框”的宽度。不再使用没有限定宽度的 `\vbox` 原语，这样可以让组合的边缘框宽度不会占满整行。不能使用 `\par` 换行的原因是 `tabular` 内部将 `\par` 置空，但又不能直接使用`p{}` 类型的单元格限定宽度，因为规定中并没有对于右侧宽度的限制。
- 现在必须依赖于 `array` 宏包，以在每一行之后插入设置行间空隙的命令（一个 2pt 深度的占位符），因为不能显式地在参数中设置诸如 `\\[2pt]` 的参数（这也将导致其他不是 `tabular` 的地方发生异常）。
- 但是使用 `\institute[]{}` 设置可以不用担心 `\\` 换行的情形，因为 beamer 在 [`\beamer@ststart`](https://github.com/josephwright/beamer/blob/865a19d4ec64f4c8e4935c19e162b8f4fd5aa190/base/beamerbasemisc.sty#L206) 宏中重定义了 `\\` 为空，当使用类似于 `\insertshortinstitute` 插入时会自动调用这一部分。所以仍然推荐使用 `\institute` 来设置。
- …
> feat: \secondaryinstlogo

- beamercolorthemesjtubeamer.sty
- beamerfontthemesjtubeamer.sty
- beamerinnerthemesjtubeamer.sty
- beamerouterthemesjtubeamer.sty
- beamerthemesjtubeamer.sty
- sjtucover.sty
- sjtuvi.sty
- src/source/beamercolorthemesjtubeamer.dtx
- src/source/beamerfontthemesjtubeamer.dtx
- src/source/beamerinnerthemesjtubeamer.dtx
- src/source/beamerouterthemesjtubeamer.dtx
- src/source/beamerthemesjtubeamer.dtx
- src/source/sjtucover.dtx
- src/source/sjtuvi.dtx
将 `stampbox` 的度量单位由 pt 改为 em，以适配不同的字号。
> refactor: stampbox measurement

- .vscode/sjtubeamer.code-snippets
- beamercolorthemesjtubeamer.sty
- beamerfontthemesjtubeamer.sty
- beamerinnerthemesjtubeamer.sty
- beamerouterthemesjtubeamer.sty
- beamerthemesjtubeamer.sty
- sjtucover.sty
- sjtuvi.sty
- src/build.lua
- src/doc/sjtubeamer.tex
- src/doc/sjtubeamerdevguide.tex
- src/source/beamercolorthemesjtubeamer.dtx
- src/source/beamerfontthemesjtubeamer.dtx
- src/source/beamerinnerthemesjtubeamer.dtx
- src/source/beamerouterthemesjtubeamer.dtx
- src/source/beamerthemesjtubeamer.dtx
- src/source/sjtucover.dtx
- src/source/sjtuvi.dtx
重构 `frametitle` 的部分度量单位，以适配不同的全局字号。并在开发文档中添加 Adaptive Layout 小节。fix #123 .
> fix: make font size option available

- .vscode/sjtubeamer.code-snippets
- beamercolorthemesjtubeamer.sty
- beamerfontthemesjtubeamer.sty
- beamerinnerthemesjtubeamer.sty
- beamerouterthemesjtubeamer.sty
- beamerthemesjtubeamer.sty
- contrib/poster/poster.tex
- contrib/poster/sjtubeamerthemeposter.ltx
- sjtucover.sty
- sjtuvi.sty
- src/doc/sjtubeamer.tex
- src/doc/sjtubeamerdevguide.tex
- src/source/beamercolorthemesjtubeamer.dtx
- src/source/beamerfontthemesjtubeamer.dtx
- src/source/beamerinnerthemesjtubeamer.dtx
- src/source/beamerouterthemesjtubeamer.dtx
- src/source/beamerthemesjtubeamer.dtx
- src/source/sjtucover.dtx
- src/source/sjtuvi.dtx
主要作样式调整：
预计在下一个 PR 发布大版本 3.0.0，将不做功能性更新，关注代码质量与文档质量的整体提升。本版本作为预发布版本，将尽可能多地修复功能性问题。
> style: fit poster, pre-release

- .github/workflows/contrib.yml
- contrib/minted/sjtubeamerthememinted.ltx
- contrib/poster/sjtubeamerthemeposter.ltx
- contrib/sjtug/sjtubeamerthemesjtug.ltx
- src/build.lua
- src/doc/sjtubeamerdevguide.tex
- src/support/newcontrib.template.tex
- src/support/sjtubeamerthemenewcontrib.template.ltx
> ci: l3build add-contrib [ci skip]

- Makefile
- src/MANIFEST.md
- src/build.lua
- src/doc/sjtubeamerdevguide.tex
添加 `make install` 命令，方便使用 Makefile 的用户将 SJTUBeamer 安装到 TeX Live 和 MacTeX 发行版中，以便全局使用。见 [水源社区的帖子](https://shuiyuan.sjtu.edu.cn/t/topic/122729)。MiKTeX 用户无法直接使用。
MANIFEST 更新最小工作集小节。
> ci: make install

- README.md
- beamercolorthemesjtubeamer.sty
- beamerfontthemesjtubeamer.sty
- beamerinnerthemesjtubeamer.sty
- beamerouterthemesjtubeamer.sty
- beamerthemesjtubeamer.sty
- contents/thesis.tex
- contrib/sjtug/sjtug.tex
- sjtucover.sty
- sjtuvi.sty
- src/doc/sjtubeamer.tex
- src/doc/sjtubeamerdevguide.tex
- src/doc/sjtubeamerquickstart.tex
- src/source/beamercolorthemesjtubeamer.dtx
- src/source/beamerfontthemesjtubeamer.dtx
- src/source/beamerinnerthemesjtubeamer.dtx
- src/source/beamerouterthemesjtubeamer.dtx
- src/source/beamerthemesjtubeamer.dtx
- src/source/beamerthemesjtubeamer.ins
- src/source/sjtucover.dtx
- src/source/sjtuvi.dtx
修复了对于头图为空的判定。加固了其他头图可能为空的情形。
Fix #155 .
> fix: if titlegraphic empty

- .github/workflows/build.yml
- .github/workflows/contrib.yml
- .github/workflows/release.yml
- main.tex
`\subject` 和 `\keywords` 没有文档中的实际作用，但会在 PDF 元数据中显示。
升级 `texlive-action` 解决了 #62, #78 不定时的 `broken pipe` 错误。
> docs: demo minor update

- .github/workflows/contrib.yml
- README.md
- README_en.md
- beamercolorthemesjtubeamer.sty
- beamerfontthemesjtubeamer.sty
- beamerinnerthemesjtubeamer.sty
- beamerouterthemesjtubeamer.sty
- beamerthemesjtubeamer.sty
- contrib/poster/poster.tex
- contrib/poster/sjtubeamerthemeposter.ltx
- sjtucover.sty
- sjtuvi.sty
- src/MANIFEST.md
- src/doc/sjtubeamer.tex
- src/doc/sjtubeamerdevguide.tex
- src/doc/sjtubeamerquickstart.tex
- src/source/beamercolorthemesjtubeamer.dtx
- src/source/beamerfontthemesjtubeamer.dtx
- src/source/beamerinnerthemesjtubeamer.dtx
- src/source/beamerouterthemesjtubeamer.dtx
- src/source/beamerthemesjtubeamer.dtx
- src/source/beamerthemesjtubeamer.ins
- src/source/sjtucover.dtx
- src/source/sjtuvi.dtx
- src/testfiles/color.tlg
- src/testfiles/inner.tlg
调整 poster 子主题的标题栏和底部栏的图案位置：
- 修复横向海报底部图案的间距；
- 修复海报标题为多行时右方图案不能与标题栏等高的问题；调整右方图案的横向宽度使其不遮挡海报标题
- 更新海报子标题的年份
更新版本至 3.1.0
- 更新测试样例
- 更新MANIFEST
- 更新年份
- 更新至 minted v3 支持的 CI 环境（进行中）
> fix: poster headline and footer

- .github/workflows/build.yml
- .github/workflows/contrib.yml
- .vscode/sjtubeamer.code-snippets
- beamercolorthemesjtubeamer.sty
- beamerfontthemesjtubeamer.sty
- beamerinnerthemesjtubeamer.sty
- beamerouterthemesjtubeamer.sty
- beamerthemesjtubeamer.sty
- sjtucover.sty
- sjtuvi.sty
- src/MANIFEST.md
- src/doc/sjtubeamer.tex
- src/doc/sjtubeamerdevguide.tex
- src/doc/sjtubeamerquickstart.tex
- src/source/beamercolorthemesjtubeamer.dtx
- src/source/beamerfontthemesjtubeamer.dtx
- src/source/beamerinnerthemesjtubeamer.dtx
- src/source/beamerouterthemesjtubeamer.dtx
- src/source/beamerthemesjtubeamer.dtx
- src/source/sjtucover.dtx
- src/source/sjtuvi.dtx
撤销 #84 中对 `\inserttitlegraphic` 的重定义，如果用户需要使用 `default` 的 `title page`，会导致其在插入 `\titlepage` 时调用 `\usebeamertemplate{titlegraphic}`，而此时 `\usebeamertemplate{titlegraphic}`(default) 会调用 `\inserttitlegraphic` 然后调用 `\usebeamertemplate{titlegraphic}`，从而导致循环调用。本 PR 将使用 `sjtutitlegraphic` 的 beamer template 来管理 SJTUBeamer “原生”的头图，并添加 `\setsjtutitlegraphic` 来初始化 `\titlegraphic`。
回退 #156 关于头图为空的判定，因为现在应当使用 `\inserttitlegraphic` 是否为空来判定。
> fix: revert \inserttitlegraphic to the original definition

- src/doc/sjtubeamer.tex
- src/support/tutorial/step17+_.tex
- src/support/tutorial/step23.tex
修复用户文档“徽标”一节二级徽标展示中额外的横向空隙，应当使用 `flush center`（基于 LaTeX `\centering`） 而不是 `center`（基于 TeX）来设置水平居中，参见 [`pgf/TikZ` 文档](https://github.com/pgf-tikz/pgf/blob/cf50fa48461e405b95b816f3208a09daa34ca8c4/doc/generic/pgf/pgfmanual-en-tikz-shapes.tex#L1014-L1050)。
修改示例学院名。
> docs: fix halign space of secondinstlogo
